### PR TITLE
fix/pass_customData_when_creating_max_ad_view

### PR DESCRIPTION
**Pull request by amondnet**
Currently we don't pass `customData` parameter when creating `MaxAdView`

https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/c6d19695e2218bae3dbbbab07477bd71faca171b/applovin_max/lib/src/max_ad_view.dart#L118

https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/c6d19695e2218bae3dbbbab07477bd71faca171b/applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXAdViewFactory.java#L55
https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/c6d19695e2218bae3dbbbab07477bd71faca171b/applovin_max/ios/Classes/AppLovinMAXAdViewFactory.m#L53

### CODE REVIEW

**Comment by thomasmso** [comment]
Looks good. Thanks!

**Comment by thomasmso** [comment]
Looks good. Thanks for the PR!

**Comment by thomasmso** [comment]
This has been released in v2.4.3

**Comment by yo1106** [comment]
I'm crashed. 
When `customData` not set.

**Comment by thomasmso** [comment]
@yo1106 - do you have the stack trace?

**Pull request merged**
