### PR TITLE
initial_implementation

### PR DESCRIPTION
**Pull request by thomasmso**
Support for inters, rewarded ads, programmatic banners and MRECs.

Docs to come, open for any questions in the meantime.

### CODE REVIEW

**Comment by thomasmso** [comment]
https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/2

**Comment by Vollinator** [comment]
Thank you very much, I love it!
Could you give us please a quick introduction how to implement the library from this repo into the flutter application?

**Comment by leatdev** [comment]
Hi @thomasmso, we appreciate your work but why it dont have native ad ? can we use MRECs as native ad ?

**Comment by thomasmso** [comment]
@Vollinator - I'll publish this later today, and
@leatdev - you can use MREC in the meantime, we don't have immediate plans to add support for Flutter native ads yet

**Pull request merged**
